# Generated by Django 5.2.16 on 2026-07-20 10:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('source', models.CharField(choices=[('FORMULAIRE_CONTACT', 'Formulaire de contact'), ('FORMULAIRE_DEVIS', 'Formulaire de devis'), ('APPEL_ENTRANT', 'Appel entrant'), ('SITE_WEB', 'Site web'), ('EVENEMENT', 'Événement')], max_length=30)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('NOUVEAU', 'Nouveau'), ('QUALIFIE', 'Qualifié'), ('PROPOSITION_EN_COURS', 'Proposition en cours'), ('PERDU', 'Perdu'), ('CONVERTI', 'Converti')], default='NOUVEAU', max_length=25)),
                ('qualification_score', models.PositiveSmallIntegerField(default=0)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['created_at'], name='marketing_l_created_c2fd89_idx'), models.Index(fields=['status'], name='marketing_l_status_f55686_idx'), models.Index(fields=['assigned_to'], name='marketing_l_assigne_cd6605_idx')],
            },
        ),
    ]
