# Generated by Django 5.2.16 on 2026-07-20 14:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('excerpt', models.TextField(blank=True)),
                ('content', models.JSONField(default=list)),
                ('visual_icon', models.CharField(blank=True, max_length=100)),
                ('visual_label', models.CharField(blank=True, max_length=255)),
                ('visual_sublabel', models.CharField(blank=True, max_length=255)),
                ('tags', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PUBLIE', 'Publié')], default='BROUILLON', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['created_at'], name='marketing_b_created_fee021_idx'), models.Index(fields=['status'], name='marketing_b_status_1dba39_idx'), models.Index(fields=['slug'], name='marketing_b_slug_dafe71_idx')],
            },
        ),
    ]
