# Generated by Django 5.2.16 on 2026-07-20 16:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_blogpost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='estimated_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image_path', models.URLField(blank=True)),
                ('additional_images', models.JSONField(default=list)),
                ('platform', models.CharField(choices=[('LINKEDIN', 'LinkedIn'), ('TWITTER', 'Twitter/X'), ('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('YOUTUBE', 'YouTube')], max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SCHEDULED', 'Programmé'), ('PUBLISHED', 'Publié'), ('FAILED', 'Échec'), ('CANCELLED', 'Annulé')], default='DRAFT', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('post_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('tags', models.JSONField(default=list)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['created_at'], name='marketing_s_created_c358dd_idx'), models.Index(fields=['status'], name='marketing_s_status_75bb84_idx'), models.Index(fields=['platform'], name='marketing_s_platfor_f77776_idx')],
            },
        ),
    ]
