# Generated by Django 5.2.16 on 2026-07-21 10:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_quote_quoteline_quote_marketing_q_created_1246ec_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.CharField(choices=[('ACCUEIL', 'Accueil')], max_length=20)),
                ('section_key', models.CharField(choices=[('hero', 'Hero'), ('services', 'Services'), ('recent_projects', 'Projets récents'), ('testimonials', 'Témoignages'), ('team', 'Équipe'), ('partner_logos', 'Logos partenaires'), ('blog_insights', 'Aperçu blog'), ('cta', 'CTA final')], max_length=30)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('kicker', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('subtitle', models.TextField(blank=True)),
                ('cta_label', models.CharField(blank=True, max_length=100)),
                ('cta_link', models.CharField(blank=True, max_length=255)),
                ('cta_secondary_label', models.CharField(blank=True, max_length=100)),
                ('cta_secondary_link', models.CharField(blank=True, max_length=255)),
                ('items', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['page', 'order'],
                'abstract': False,
                'indexes': [models.Index(fields=['created_at'], name='marketing_p_created_05f8f9_idx'), models.Index(fields=['page'], name='marketing_p_page_ed76f3_idx')],
                'constraints': [models.UniqueConstraint(fields=('page', 'section_key'), name='unique_page_section')],
            },
        ),
    ]
