# Generated by Django 5.2.16 on 2026-07-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0006_seed_page_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesection',
            name='page',
            field=models.CharField(choices=[('ACCUEIL', 'Accueil'), ('EXPERTISE', 'Expertise'), ('SUIVI_PROJET', 'Suivi de projet')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='section_key',
            field=models.CharField(choices=[('hero', 'Hero'), ('services', 'Services'), ('recent_projects', 'Projets récents'), ('testimonials', 'Témoignages'), ('team', 'Équipe'), ('partner_logos', 'Logos partenaires'), ('blog_insights', 'Aperçu blog'), ('cta', 'CTA final'), ('expertise_hero', 'Hero (Expertise)'), ('strategic_advantages', 'Avantages stratégiques'), ('process_timeline', 'Processus'), ('tech_stack', 'Stack technique'), ('featured_case_study', 'Étude de cas vedette'), ('tracking_hero', 'Hero (Suivi de projet)'), ('tracking_features', 'Fonctionnalités mises en avant')], max_length=30),
        ),
    ]
