# Generated by Django 5.2.16 on 2026-07-21 17:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0008_seed_expertise_and_tracking_sections'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowcaseProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('category', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('featured', models.BooleanField(default=False)),
                ('show_on_homepage', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('status_tag', models.CharField(blank=True, max_length=100)),
                ('tag', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('visual_icon', models.CharField(blank=True, max_length=100)),
                ('video_src', models.URLField(blank=True)),
                ('images', models.JSONField(blank=True, default=list)),
                ('scene_variants', models.JSONField(blank=True, default=list)),
                ('client', models.CharField(blank=True, max_length=255)),
                ('technologies', models.JSONField(blank=True, default=list)),
                ('timeline', models.CharField(blank=True, max_length=255)),
                ('lead_name', models.CharField(blank=True, max_length=255)),
                ('lead_role', models.CharField(blank=True, max_length=255)),
                ('challenge', models.TextField(blank=True)),
                ('stats', models.JSONField(blank=True, default=list)),
                ('solution', models.TextField(blank=True)),
                ('solution_points', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['order', '-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['created_at'], name='marketing_s_created_5c88bc_idx'), models.Index(fields=['slug'], name='marketing_s_slug_4f5b17_idx'), models.Index(fields=['show_on_homepage'], name='marketing_s_show_on_eb9aca_idx')],
            },
        ),
    ]
