# Generated by Django 5.2.16 on 2026-07-21 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0011_clear_nova_finance_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcaseproject',
            name='project_url',
            field=models.URLField(blank=True),
        ),
    ]
