# Generated by Django 5.2.16 on 2026-07-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0012_showcaseproject_project_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='visual_image',
            field=models.URLField(blank=True),
        ),
    ]
