# Generated by Django 5.2.16 on 2026-07-23 16:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0015_simplify_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logo_url', models.URLField(blank=True)),
                ('tagline', models.TextField(blank=True)),
                ('nav_links', models.JSONField(blank=True, default=list)),
                ('services_links', models.JSONField(blank=True, default=list)),
                ('legal_links', models.JSONField(blank=True, default=list)),
                ('social_links', models.JSONField(blank=True, default=list)),
                ('copyright_text', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['created_at'], name='marketing_s_created_75939c_idx')],
            },
        ),
    ]
