# Generated by Django 5.2.16 on 2026-07-23 20:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0019_seed_start_project_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='client_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quote',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='intro_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='payment_terms',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='quote',
            name='project_duration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quote',
            name='subject',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='quoteline',
            name='amount_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quoteline',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='QuoteSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_address', models.TextField(blank=True)),
                ('company_phone', models.CharField(blank=True, max_length=100)),
                ('company_email', models.CharField(blank=True, max_length=255)),
                ('payment_methods', models.JSONField(blank=True, default=list)),
                ('default_payment_terms', models.JSONField(blank=True, default=list)),
                ('footer_note', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['created_at'], name='marketing_q_created_71fea5_idx')],
            },
        ),
    ]
