# Generated by Django 5.2.16 on 2026-08-16 10:50

import django.db.models.deletion
import django_cryptography.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0021_seed_quote_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='reminders_sent',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='platform',
            field=models.CharField(choices=[('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram')], max_length=20),
        ),
        migrations.CreateModel(
            name='SocialMediaCredentials',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facebook_page_id', models.CharField(blank=True, max_length=100)),
                ('facebook_access_token', django_cryptography.fields.encrypt(models.TextField(blank=True))),
                ('instagram_business_account_id', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['created_at'], name='marketing_s_created_ecc475_idx')],
            },
        ),
    ]
