# Generated by Django 5.2.16 on 2026-08-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0022_socialpost_reminders_sent_alter_socialpost_platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='accepted_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
