# Generated by Django 5.2.16 on 2026-08-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0023_quote_accepted_ip_quote_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotesettings',
            name='company_stamp_url',
            field=models.URLField(blank=True),
        ),
    ]
