# Generated by Django 5.2.16 on 2026-08-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0024_quotesettings_company_stamp_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='document_color',
            field=models.CharField(default='#123f91', max_length=7),
        ),
        migrations.AddField(
            model_name='quote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
