# Generated by Django 5.2.16 on 2026-08-16 14:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0025_quote_document_color_quote_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('spec_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('spec_type', models.CharField(choices=[('FONCTIONNEL', 'Fonctionnel'), ('TECHNIQUE', 'Technique')], max_length=15)),
                ('title', models.CharField(max_length=255)),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('intro_message', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('document_color', models.CharField(default='#123f91', max_length=7)),
                ('status', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('FINALISE', 'Finalisé')], default='BROUILLON', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpecificationLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interface_name', models.CharField(max_length=255)),
                ('objective', models.TextField()),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='marketing.specification')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='specification',
            index=models.Index(fields=['created_at'], name='marketing_s_created_5fd42f_idx'),
        ),
        migrations.AddIndex(
            model_name='specification',
            index=models.Index(fields=['spec_type'], name='marketing_s_spec_ty_82b581_idx'),
        ),
        migrations.AddIndex(
            model_name='specification',
            index=models.Index(fields=['created_by'], name='marketing_s_created_4dd69c_idx'),
        ),
        migrations.AddIndex(
            model_name='specificationline',
            index=models.Index(fields=['created_at'], name='marketing_s_created_af1f97_idx'),
        ),
    ]
