# Generated by Django 5.2.16 on 2026-08-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0027_socialpost_status_francais'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='signature_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
