# Generated by Django 5.2.16 on 2026-09-09 09:09

from django.db import migrations, models


def seed_sequence_from_existing_references(apps, schema_editor):
    """Fait démarrer la séquence après la dernière référence déjà attribuée.

    Sans cela, la première demande postérieure à cette migration repartirait
    de 1 et reprendrait une référence déjà envoyée par e-mail.
    """
    Lead = apps.get_model('marketing', 'Lead')
    Sequence = apps.get_model('marketing', 'LeadReferenceSequence')

    highest = {}
    for reference in Lead.objects.exclude(tracking_reference='').values_list(
        'tracking_reference', flat=True,
    ):
        try:
            _, year, counter = reference.split('-')
            year, counter = int(year), int(counter)
        except (ValueError, TypeError):
            continue
        highest[year] = max(highest.get(year, 0), counter)

    for year, last_value in highest.items():
        Sequence.objects.update_or_create(year=year, defaults={'last_value': last_value})


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0029_lead_tracking_reference_lead_tracking_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadReferenceSequence',
            fields=[
                ('year', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RunPython(seed_sequence_from_existing_references, noop),
    ]
