# Generated by Django 5.2.16 on 2026-09-09 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0030_leadreferencesequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='marketing.specification'),
        ),
        migrations.AddField(
            model_name='lead',
            name='workflow_stage',
            field=models.CharField(choices=[('SOUMIS', 'Soumis'), ('CHEZ_TECHNIQUE', 'En analyse technique'), ('CDC_PRET', 'Cahier des charges prêt'), ('SOUMIS_CLIENT', 'Soumis au client'), ('VALIDE_CLIENT', 'Validé par le client'), ('EN_DEVELOPPEMENT', 'En développement')], default='SOUMIS', max_length=20),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['workflow_stage'], name='marketing_l_workflo_3860e3_idx'),
        ),
    ]
