# Generated by Django 5.2.16 on 2026-09-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0031_lead_specification_lead_workflow_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='attachment_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='attachment_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
    ]
