# Generated by Django 5.2.16 on 2026-09-10 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0032_lead_attachment_name_lead_attachment_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
