# Generated by Django 5.2.16 on 2026-07-20 17:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('SOUMIS', 'Soumis'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], default='SOUMIS', max_length=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'abstract': False,
                'indexes': [models.Index(fields=['created_at'], name='projects_ti_created_641c8f_idx'), models.Index(fields=['project', 'status'], name='projects_ti_project_ce157c_idx'), models.Index(fields=['user', 'date'], name='projects_ti_user_id_980429_idx')],
                'constraints': [models.UniqueConstraint(fields=('project', 'user', 'date'), name='unique_timesheet_per_day')],
            },
        ),
    ]
