# Generated by Django 5.2.16 on 2026-08-11 12:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_category_project_is_archived_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTaskComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField()),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.RemoveIndex(
            model_name='projecttask',
            name='projects_pr_project_da2a5c_idx',
        ),
        migrations.RemoveField(
            model_name='projecttask',
            name='is_done',
        ),
        migrations.AddField(
            model_name='projecttask',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='project_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='status',
            field=models.CharField(choices=[('TODO', 'À faire'), ('IN_PROGRESS', 'En cours'), ('IN_REVIEW', 'En révision'), ('DONE', 'Terminé')], default='TODO', max_length=20),
        ),
        migrations.AddIndex(
            model_name='projecttask',
            index=models.Index(fields=['project', 'status'], name='projects_pr_project_4795b4_idx'),
        ),
        migrations.AddField(
            model_name='projecttaskcomment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_task_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projecttaskcomment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.projecttask'),
        ),
        migrations.AddIndex(
            model_name='projecttaskcomment',
            index=models.Index(fields=['created_at'], name='projects_pr_created_77a18c_idx'),
        ),
    ]
