"""
Django settings for sokens_backend project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
import sys
import dj_database_url
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Loads variables from a local .env file if present. Never overrides
# variables already set in the real environment (e.g. by Render or Docker).
load_dotenv(BASE_DIR / '.env')


def _env_bool(name, default=False):
    return os.environ.get(name, str(default)).strip().lower() in ('1', 'true', 'yes', 'on')


def _env_list(name, default=''):
    raw = os.environ.get(name, default)
    return [item.strip() for item in raw.split(',') if item.strip()]


# SECURITY WARNING: keep the secret key used in production secret!
# The fallback below is only ever used for local development / Docker build
# steps (e.g. collectstatic) and must be overridden via the SECRET_KEY env
# var in any real deployment.
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-pr8^&i!kn23(a_^#jk*8%=&eu4fu27g46+setd+21k)#4tmx0k',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool('DEBUG', default=False)

ALLOWED_HOSTS = _env_list('ALLOWED_HOSTS', default='localhost,127.0.0.1')

# Render sets this automatically for every web service; trust it so the
# deployed backend works without having to hardcode its hostname.
_render_host = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if _render_host and _render_host not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(_render_host)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_filters',
    'drf_spectacular',
    'corsheaders',
    'core',
    'projects',
    'hr',
    'marketing',
    'finance',
]

AUTH_USER_MODEL = 'core.User'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# In local development it's convenient to allow every origin. In any real
# deployment, set CORS_ALLOWED_ORIGINS (comma-separated) instead — e.g. the
# Vercel/Render URL of the Next.js frontend.
CORS_ALLOW_ALL_ORIGINS = DEBUG
CORS_ALLOWED_ORIGINS = _env_list('CORS_ALLOWED_ORIGINS')

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'core.authentication.FirebaseAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 25,
}

SPECTACULAR_SETTINGS = {
    'TITLE': "Soken's Digital API",
    'DESCRIPTION': "API backend de Soken's Digital — gestion des utilisateurs, projets et suivi client.",
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    # Explicit order + descriptions for the Swagger UI sidebar grouping —
    # every endpoint below is tagged via @extend_schema(tags=[...]) to match
    # one of these, one section per département (docs/backend-specifications.md).
    'TAGS': [
        {'name': 'Système', 'description': 'Liveness check et autres endpoints transverses.'},
        {'name': 'Authentification', 'description': 'Profil du compte connecté (/auth/me/).'},
        {
            'name': 'Administration & RH',
            'description': "Utilisateurs, départements, dossiers employés, contrats, fiches de paie.",
        },
        {'name': 'Technique & Projets', 'description': 'Projets et membres.'},
        {'name': 'Marketing & Commercial', 'description': 'Leads, devis, CMS, réseaux sociaux.'},
    ],
    'SORT_OPERATIONS': False,
}

ROOT_URLCONF = 'sokens_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sokens_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
]

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Cache (also used to memoize dashboard aggregations behind a TTL, and for
# rate limiting — see marketing/ratelimit.py).
REDIS_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')

# `manage.py test` shouldn't depend on a live Redis (not always running
# locally, e.g. outside docker-compose) — fall back to an in-memory cache
# so cache-dependent code (rate limiting, dashboard TTLs) is still
# exercised by tests without requiring external infra.
if 'test' in sys.argv:
    CACHES = {'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'}}
else:
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': REDIS_URL,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            },
        }
    }

# Celery — broker and result backend share the same Redis instance as the
# cache (different logical DBs would be overkill at this project's scale).
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Firebase Admin SDK (server-side) credentials. Set one of:
# - FIREBASE_SERVICE_ACCOUNT_JSON: the full service account JSON as a
#   single-line string (used on Render, where mounting a file isn't
#   convenient).
# - GOOGLE_APPLICATION_CREDENTIALS: a filesystem path to the service
#   account JSON (used locally / in Docker via a mounted file).
# Actual initialization happens in core.apps.CoreConfig.ready().
