"""
Django settings for sokens_backend project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
import sys
import dj_database_url
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Loads variables from a local .env file if present. Never overrides
# variables already set in the real environment (e.g. by Render or Docker).
load_dotenv(BASE_DIR / '.env')


def _env_bool(name, default=False):
    return os.environ.get(name, str(default)).strip().lower() in ('1', 'true', 'yes', 'on')


def _env_list(name, default=''):
    raw = os.environ.get(name, default)
    return [item.strip() for item in raw.split(',') if item.strip()]


_INSECURE_SECRET_KEY_FALLBACK = 'django-insecure-pr8^&i!kn23(a_^#jk*8%=&eu4fu27g46+setd+21k)#4tmx0k'

# SECURITY WARNING: keep the secret key used in production secret!
# The fallback below is only ever used for local development / Docker build
# steps (e.g. collectstatic) and must be overridden via the SECRET_KEY env
# var in any real deployment.
SECRET_KEY = os.environ.get('SECRET_KEY', _INSECURE_SECRET_KEY_FALLBACK)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool('DEBUG', default=False)

# Refuse to boot with the checked-in fallback key once DEBUG is off — a
# stolen/leaked SECRET_KEY lets an attacker forge session cookies, password
# reset tokens and the `signed_cookies` session backend. Failing loudly at
# startup is strictly better than silently running production on a key
# that's sitting in git history for anyone to read.
if not DEBUG and SECRET_KEY == _INSECURE_SECRET_KEY_FALLBACK:
    raise RuntimeError(
        'SECRET_KEY env var is not set (or still the insecure dev default) '
        'while DEBUG=False. Refusing to start — set a real SECRET_KEY.'
    )

ALLOWED_HOSTS = _env_list('ALLOWED_HOSTS', default='localhost,127.0.0.1')

# Render sets this automatically for every web service; trust it so the
# deployed backend works without having to hardcode its hostname.
_render_host = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if _render_host and _render_host not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(_render_host)

# Django's own default logging config only wires the console handler when
# DEBUG=True, so unhandled 500s were vanishing silently in production (no
# ADMINS/email backend configured either) — nothing in Render's logs to
# debug from. This makes every unhandled request exception print its full
# traceback to stdout regardless of DEBUG, which is what platform log tools
# (Render, etc.) capture.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_filters',
    'drf_spectacular',
    'corsheaders',
    'core',
    'projects',
    'hr',
    'marketing',
    'finance',
    'technique',
    'administration',
    'messaging',
    'procurement',
    'treasury',
]

AUTH_USER_MODEL = 'core.User'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# In local development it's convenient to allow every origin. In any real
# deployment, set CORS_ALLOWED_ORIGINS (comma-separated) instead — e.g. the
# Vercel/Render URL of the Next.js frontend. CORS_ALLOW_ALL_ORIGINS is tied
# to DEBUG so a misconfigured prod deploy (forgot to set CORS_ALLOWED_ORIGINS)
# fails closed (no origin allowed) rather than open (every origin allowed).
CORS_ALLOW_ALL_ORIGINS = DEBUG
CORS_ALLOWED_ORIGINS = _env_list('CORS_ALLOWED_ORIGINS')
CORS_ALLOW_CREDENTIALS = True

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'core.authentication.FirebaseAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 25,
    # Global abuse-prevention floor. Individual public/sensitive views
    # (webhooks, public devis/contact forms, auth-adjacent endpoints) layer
    # a tighter scoped throttle on top — see core.throttles.
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': os.environ.get('THROTTLE_RATE_ANON', '100/hour'),
        'user': os.environ.get('THROTTLE_RATE_USER', '2000/hour'),
        'public_write': os.environ.get('THROTTLE_RATE_PUBLIC_WRITE', '10/hour'),
        'webhook': os.environ.get('THROTTLE_RATE_WEBHOOK', '60/min'),
    },
}

# ---------------------------------------------------------------------------
# Durcissement sécurité — actif uniquement quand DEBUG=False (prod/staging).
# Rien de ceci ne gêne le développement local (DEBUG=True par défaut).
# ---------------------------------------------------------------------------
if not DEBUG:
    # Render (et la plupart des PaaS) terminent TLS au niveau du proxy et
    # relaient en HTTP en interne — sans ce header, Django croit que la
    # requête est en clair et boucle sur SECURE_SSL_REDIRECT.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    # HSTS : force HTTPS côté navigateur pour toute visite future, même si
    # l'utilisateur tape http:// ou suit un vieux lien. 1 an, sous-domaines
    # inclus — valeur standard pour un premier déploiement conforme aux
    # exigences de preload sans s'y inscrire tout de suite (SECURE_HSTS_PRELOAD
    # est un engagement à sens unique difficile à annuler, laissé à False).
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = False
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = 'same-origin'
    X_FRAME_OPTIONS = 'DENY'

SPECTACULAR_SETTINGS = {
    'TITLE': "Soken's Digital API",
    'DESCRIPTION': "API backend de Soken's Digital — gestion des utilisateurs, projets et suivi client.",
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    # Explicit order + descriptions for the Swagger UI sidebar grouping —
    # every endpoint below is tagged via @extend_schema(tags=[...]) to match
    # one of these, one section per département (docs/backend-specifications.md).
    'TAGS': [
        {'name': 'Système', 'description': 'Liveness check et autres endpoints transverses.'},
        {'name': 'Authentification', 'description': 'Profil du compte connecté (/auth/me/).'},
        {
            'name': 'Administration & RH',
            'description': "Utilisateurs, départements, dossiers employés, contrats, fiches de paie.",
        },
        {'name': 'Technique & Projets', 'description': 'Projets, membres, timesheets.'},
        {'name': 'Marketing & Commercial', 'description': 'Leads, devis, CMS, réseaux sociaux.'},
        {
            'name': 'Finance & Comptabilité',
            'description': 'Décaissements, clôture comptable, Grand Livre, facturation, rapprochement bancaire, TVA.',
        },
    ],
    'SORT_OPERATIONS': False,
}

# Celery settings
CELERY_BROKER_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_BEAT_SCHEDULE = {
    'technique-check-budget-alerts': {
        'task': 'technique.tasks.check_budget_alerts',
        'schedule': 3600.0,  # toutes les heures
    },
    'technique-interaction-follow-up-reminders': {
        'task': 'administration.tasks.follow_up_reminders',
        'schedule': 3600.0,
    },
    'administration-document-expiry-check': {
        'task': 'administration.tasks.document_expiry',
        'schedule': 86400.0,  # une fois par jour
    },
}

# Email — utilisé par technique.tasks.send_ticket_resolution_email et les
# alertes d'expiration de documents RH. EMAIL_BACKEND par défaut = console
# (affiche l'email dans les logs, aucun envoi réel) tant que EMAIL_HOST
# n'est pas configuré — évite un crash au démarrage/dans les tests si SMTP
# n'est pas disponible, tout en gardant le code d'envoi actif.
if os.environ.get('EMAIL_HOST'):
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.environ.get('EMAIL_HOST')
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
    EMAIL_USE_TLS = _env_bool('EMAIL_USE_TLS', default=True)
    EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'no-reply@sokensdigital.com')

ROOT_URLCONF = 'sokens_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sokens_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
]

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Cache (also used to memoize dashboard aggregations behind a TTL, and for
# rate limiting — see marketing/ratelimit.py).
REDIS_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')

# Tests shouldn't depend on a live Redis (not always running locally, e.g.
# outside docker-compose) — fall back to an in-memory cache so
# cache-dependent code (rate limiting via DRF throttle classes, dashboard
# TTLs) is still exercised by tests without requiring external infra.
# `'test' in sys.argv` only catches `manage.py test` — pytest (this repo's
# actual test runner, see backend/pytest.ini) never puts 'test' in argv,
# so PYTEST_CURRENT_TEST (set by pytest for the duration of every test) is
# the check that actually matters here.
if 'test' in sys.argv or 'PYTEST_CURRENT_TEST' in os.environ or 'pytest' in sys.modules:
    CACHES = {'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'}}
else:
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': REDIS_URL,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            },
        }
    }

# Celery — broker and result backend share the same Redis instance as the
# cache (different logical DBs would be overkill at this project's scale).
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Celery Beat — tâches programmées (daily cron jobs)
from celery.schedules import crontab
CELERY_BEAT_SCHEDULE = {
    'send-invoice-reminders': {
        'task': 'finance.tasks.send_invoice_reminders',
        'schedule': crontab(hour=9, minute=0),  # 09:00 UTC chaque jour
        'options': {'queue': 'default'}
    },
    'check-budget-alerts': {
        'task': 'technique.tasks.check_budget_alerts',
        'schedule': crontab(hour=10, minute=0),  # 10:00 UTC chaque jour
        'options': {'queue': 'default'}
    },
}

# Facebook Page publishing (marketing/publishing.py) — blank by default,
# nothing publishes until both are set. FACEBOOK_PAGE_ACCESS_TOKEN must be
# a long-lived PAGE access token (not a User token, those expire in ~1-2h),
# generated once via Graph API Explorer / a "Facebook Login for Business"
# flow and pasted here — see the setup checklist for the exact steps.
FACEBOOK_PAGE_ID = os.environ.get('FACEBOOK_PAGE_ID', '')
FACEBOOK_PAGE_ACCESS_TOKEN = os.environ.get('FACEBOOK_PAGE_ACCESS_TOKEN', '')

# Shared secret for the e-signature provider's webhook (administration app,
# SignatureWebhookView). Blank by default — the webhook returns 503 until
# this is set, rather than accepting unsigned callbacks. Must match the
# secret configured on the provider side (HMAC-SHA256 over the raw request
# body, sent back in the X-Signature header).
SIGNATURE_WEBHOOK_SECRET = os.environ.get('SIGNATURE_WEBHOOK_SECRET', '')

# Gmail API (core/email_gmail.py) — used instead of SMTP because Render's
# free plan blocks outbound SMTP ports; the Gmail API talks HTTPS instead.
# GMAIL_REFRESH_TOKEN is obtained once via scripts/generate_gmail_refresh_
# token.py (a local, interactive OAuth consent flow) and never expires
# unless revoked — GMAIL_CLIENT_ID/SECRET come from the same Google Cloud
# OAuth client (type "Desktop app") used to generate it. Blank by default;
# core.notifications.notify(..., email=True) silently skips sending until
# all three are set.
GMAIL_CLIENT_ID = os.environ.get('GMAIL_CLIENT_ID', '')
GMAIL_CLIENT_SECRET = os.environ.get('GMAIL_CLIENT_SECRET', '')
GMAIL_REFRESH_TOKEN = os.environ.get('GMAIL_REFRESH_TOKEN', '')
GMAIL_SENDER_EMAIL = os.environ.get('GMAIL_SENDER_EMAIL', '')

# Firebase Admin SDK (server-side) credentials. Set one of:
# - FIREBASE_SERVICE_ACCOUNT_JSON: the full service account JSON as a
#   single-line string (used on Render, where mounting a file isn't
#   convenient).
# - GOOGLE_APPLICATION_CREDENTIALS: a filesystem path to the service
#   account JSON (used locally / in Docker via a mounted file).
# Actual initialization happens in core.apps.CoreConfig.ready().
