# Generated by Django 5.2.16 on 2026-07-20 17:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_timesheet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisbursementRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('beneficiary', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('EN_ATTENTE_N1', 'En attente (N1)'), ('EN_ATTENTE_N2', 'En attente (N2)'), ('APPROUVE', 'Approuvé'), ('REJETE', 'Rejeté'), ('EXECUTE', 'Exécuté')], default='EN_ATTENTE_N1', max_length=20)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursement_requests', to='projects.project')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursement_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['created_at'], name='finance_dis_created_ea164c_idx'), models.Index(fields=['status'], name='finance_dis_status_91d4e9_idx'), models.Index(fields=['project'], name='finance_dis_project_120a3e_idx')],
            },
        ),
    ]
