# Generated by Django 5.2.16 on 2026-07-20 20:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursementrequest',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disbursementrequest',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_disbursements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disbursementrequest',
            name='executed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disbursementrequest',
            name='executed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_disbursements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('account_class', models.CharField(choices=[('ACTIF', 'Actif'), ('PASSIF', 'Passif'), ('CHARGE', 'Charge'), ('PRODUIT', 'Produit'), ('TVA', 'TVA')], max_length=10)),
            ],
            options={
                'ordering': ['code'],
                'abstract': False,
                'indexes': [models.Index(fields=['created_at'], name='finance_acc_created_c4c98b_idx'), models.Index(fields=['code'], name='finance_acc_code_75c62f_idx')],
            },
        ),
        migrations.CreateModel(
            name='AccountingPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('label', models.CharField(help_text='Ex: 2026-07', max_length=20, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('OUVERTE', 'Ouverte'), ('CLOTUREE', 'Clôturée')], default='OUVERTE', max_length=10)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BankStatementImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=255)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('client_name', models.CharField(max_length=255)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('amount_ht', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('0.18'), max_digits=4)),
                ('amount_ttc', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('status', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDEE', 'Validée')], default='BROUILLON', max_length=10)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issue_date', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal_code', models.CharField(choices=[('VE', 'Ventes'), ('AC', 'Achats'), ('BQ', 'Banque'), ('OD', 'Opérations diverses')], max_length=2)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('label', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='finance.accountingperiod')),
                ('source_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='finance.invoice')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaxDeclaration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDEE', 'Validée')], default='BROUILLON', max_length=10)),
                ('collected_vat', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('deductible_vat', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('net_vat', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_tax_declarations', to=settings.AUTH_USER_MODEL)),
                ('period', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_declaration', to='finance.accountingperiod')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_tax_declarations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('lettrage_code', models.CharField(blank=True, max_length=40)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='finance.account')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.journalentry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('label', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('NON_LETTRE', 'Non lettré'), ('LETTRE', 'Lettré')], default='NON_LETTRE', max_length=12)),
                ('statement_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.bankstatementimport')),
                ('matched_line', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_bank_transaction', to='finance.transactionline')),
            ],
            options={
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='accountingperiod',
            index=models.Index(fields=['created_at'], name='finance_acc_created_b52f8c_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingperiod',
            index=models.Index(fields=['status'], name='finance_acc_status_fe4ec8_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatementimport',
            index=models.Index(fields=['created_at'], name='finance_ban_created_ad66ba_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['created_at'], name='finance_inv_created_6e1634_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='finance_inv_status_d9b47e_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['created_at'], name='finance_jou_created_5071fb_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['period'], name='finance_jou_period__84c4bb_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['journal_code'], name='finance_jou_journal_5a13c7_idx'),
        ),
        migrations.AddIndex(
            model_name='taxdeclaration',
            index=models.Index(fields=['created_at'], name='finance_tax_created_0c2aa6_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionline',
            index=models.Index(fields=['created_at'], name='finance_tra_created_0c4cb0_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionline',
            index=models.Index(fields=['account'], name='finance_tra_account_54fea1_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['created_at'], name='finance_ban_created_006a24_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['status'], name='finance_ban_status_95459b_idx'),
        ),
    ]
