# Generated by Django 5.2.16 on 2026-08-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_disbursementrequest_decided_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursementrequest',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='disbursementrequest',
            name='status',
            field=models.CharField(choices=[('EN_ATTENTE_N1', 'En attente (N1)'), ('EN_ATTENTE_N2', 'En attente (N2)'), ('EN_ATTENTE_N3', 'En attente (N3)'), ('APPROUVE', 'Approuvé'), ('REJETE', 'Rejeté'), ('EXECUTE', 'Exécuté')], default='EN_ATTENTE_N1', max_length=20),
        ),
    ]
