# Generated by Django 5.2.16 on 2026-08-16 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_disbursementrequest_rejection_reason_and_more'),
        ('marketing', '0023_quote_accepted_ip_quote_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='marketing.quote'),
        ),
    ]
