# Generated by Django 5.2.16 on 2026-08-17 01:49

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_financesettings_treasury_accounts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date', '-created_at']},
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='finance_pay_invoice_80fc36_idx',
            old_name='finance_pay_invoice_a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='finance_pay_payment_72f761_idx',
            old_name='finance_pay_payment_x9y8z7_idx',
        ),
        migrations.AlterField(
            model_name='financesettings',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.18'), help_text='Taux TVA appliqué par défaut aux nouvelles factures (ex: 0.18 = 18%)', max_digits=4),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='finance_pay_created_859d0d_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentreceipt',
            index=models.Index(fields=['created_at'], name='finance_pay_created_25e312_idx'),
        ),
    ]
