# Generated by Django 5.2.16 on 2026-09-09 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def remap_tiered_statuses(apps, schema_editor):
    """Le circuit à trois paliers (N1/N2/N3, indexé sur le montant) est
    remplacé par le circuit fixe RCF -> Gérant du process comptable
    officiel, qui ne prévoit aucun seuil.

    Une demande encore en attente sous l'ancien système repasse par la RCF,
    quel que soit son ancien palier — y compris une ex-N3, qui aurait sauté
    l'étape RCF sous l'ancien système alors que le document l'exige pour
    toute demande. Une demande déjà tranchée (approuvée, rejetée, exécutée)
    n'est pas touchée : son statut reste correct sous les deux systèmes.
    """
    DisbursementRequest = apps.get_model('finance', 'DisbursementRequest')
    DisbursementRequest.objects.filter(
        status__in=['EN_ATTENTE_N1', 'EN_ATTENTE_N2', 'EN_ATTENTE_N3'],
    ).update(status='EN_ATTENTE_RCF')


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_alter_payment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursementrequest',
            name='rcf_decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disbursementrequest',
            name='rcf_decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rcf_decided_disbursements', to=settings.AUTH_USER_MODEL),
        ),
        # Le remappage doit précéder l'AlterField : une fois les choices
        # restreints aux nouvelles valeurs, une ligne encore sur
        # EN_ATTENTE_N1/N2/N3 ne serait plus qu'une valeur invalide.
        migrations.RunPython(remap_tiered_statuses, noop),
        migrations.AlterField(
            model_name='disbursementrequest',
            name='status',
            field=models.CharField(choices=[('EN_ATTENTE_RCF', 'En attente RCF'), ('EN_ATTENTE_GERANT', 'En attente Gérant'), ('APPROUVE', 'Approuvé'), ('REJETE', 'Rejeté'), ('EXECUTE', 'Exécuté')], default='EN_ATTENTE_RCF', max_length=20),
        ),
    ]
