# Generated by Django 5.2.16 on 2026-08-17 01:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_alter_payment_options_and_more'),
        ('procurement', '0003_rename_procurement_p_status_x9y8z7_idx_procurement_status_146396_idx_and_more'),
        ('treasury', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bankentry',
            new_name='treasury_ba_type_ae1b89_idx',
            old_name='treasury_b_type_s_source_idx',
        ),
        migrations.RenameIndex(
            model_name='bankentry',
            new_name='treasury_ba_date_c73f5b_idx',
            old_name='treasury_b_date_idx',
        ),
        migrations.RenameIndex(
            model_name='cashentry',
            new_name='treasury_ca_type_023623_idx',
            old_name='treasury_c_type_s_source_idx',
        ),
        migrations.RenameIndex(
            model_name='cashentry',
            new_name='treasury_ca_date_48f083_idx',
            old_name='treasury_c_date_idx',
        ),
        migrations.AddIndex(
            model_name='bankentry',
            index=models.Index(fields=['created_at'], name='treasury_ba_created_8cf1a6_idx'),
        ),
        migrations.AddIndex(
            model_name='capitalcontribution',
            index=models.Index(fields=['created_at'], name='treasury_ca_created_50169c_idx'),
        ),
        migrations.AddIndex(
            model_name='cashentry',
            index=models.Index(fields=['created_at'], name='treasury_ca_created_a48cdb_idx'),
        ),
    ]
