# Generated by Django 5.2.16 on 2026-08-31 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0002_rename_treasury_b_type_s_source_idx_treasury_ba_type_ae1b89_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankentry',
            name='source',
            field=models.CharField(choices=[('APPORT_CAPITAL', 'Apport capital'), ('CLIENT_CHEQUE', 'Client paie chèque'), ('CLIENT_VIREMENT', 'Client paie virement'), ('CAISSE_DEPOT', 'Dépôt espèces caisse'), ('FOURNISSEUR_CHEQUE', 'Paiement fournisseur chèque'), ('FOURNISSEUR_VIREMENT', 'Paiement fournisseur virement'), ('RETRAIT_ESPECES', 'Retrait espèces'), ('AUTRE', 'Autre')], max_length=30),
        ),
    ]
