# Generated by Django 5.2.16 on 2026-07-21 07:47

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_name', models.CharField(max_length=255)),
                ('siret', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('sector', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('PROSPECT', 'Prospect'), ('CLIENT_ACTIF', 'Client Actif'), ('CLIENT_INACTIF', 'Client Inactif'), ('ARCHIVE', 'Archivé')], default='PROSPECT', max_length=20)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_type', models.CharField(choices=[('CONTRAT', 'Contrat'), ('DEVIS', 'Devis'), ('FACTURE', 'Facture'), ('AUTRE_JURIDIQUE', 'Autre juridique')], max_length=20)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interaction_type', models.CharField(choices=[('CALL', 'Appel'), ('EMAIL', 'Email'), ('MEETING', 'Réunion'), ('OTHER', 'Autre')], max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('notes', models.TextField()),
                ('follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset_name', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=255, unique=True)),
                ('asset_type', models.CharField(choices=[('ORDINATEUR', 'Ordinateur'), ('TELEPHONE', 'Téléphone'), ('ECRAN', 'Ecran'), ('CLAVIER', 'Clavier'), ('SOURIS', 'Souris'), ('MOBILIER', 'Mobilier'), ('AUTRE', 'Autre')], max_length=20)),
                ('condition_status', models.CharField(choices=[('NEUF', 'Neuf'), ('BON', 'Bon état'), ('USAGE', 'Usagé'), ('REPARATION', 'En réparation'), ('HORS_SERVICE', 'Hors service')], max_length=20)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContractGenerator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract_type', models.CharField(choices=[('PRESTATION_SERVICES', 'Prestation de services'), ('NDA', 'NDA'), ('CDI', 'CDI'), ('CDD', 'CDD')], max_length=30)),
                ('template_data', models.JSONField(blank=True, default=dict)),
                ('generated_file_path', models.CharField(blank=True, max_length=500)),
                ('signing_status', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_ATTENTE_DE_SIGNATURE', 'En attente de signature'), ('SIGNE', 'Signé'), ('EXPIRE', 'Expiré')], default='BROUILLON', max_length=30)),
                ('envelope_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('document_type', models.CharField(choices=[('CONTRAT_TRAVAIL', 'Contrat de travail'), ('FICHE_PAIE', 'Fiche de paie'), ('ATTESTATION', 'Attestation'), ('DIPLOME', 'Diplôme'), ('AUTRE', 'Autre')], max_length=20)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leave_type', models.CharField(choices=[('CONGE_PAYE', 'Congé payé'), ('MALADIE', 'Maladie'), ('SANS_SOLDE', 'Sans solde'), ('RTT', 'RTT'), ('EXCEPTIONNEL', 'Exceptionnel')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_ATTENTE', 'En attente'), ('APPROUVE', 'Approuvé'), ('REJETE', 'Rejeté')], default='BROUILLON', max_length=20)),
                ('reason', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdministrativeRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('record_type', models.CharField(choices=[('PV_ASSEMBLEE', 'PV Assemblée'), ('NOTE_SERVICE', 'Note de service'), ('DECISION_DIRECTION', 'Décision direction')], max_length=30)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('content', models.TextField(blank=True)),
                ('is_public_internally', models.BooleanField(default=False)),
                ('is_finalized', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['created_at'], name='administrat_created_9971d8_idx')],
            },
        ),
    ]
