# Generated by Django 5.2.16 on 2026-07-21 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='administration.client'),
        ),
        migrations.AddField(
            model_name='clientdocument',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_client_docs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientinteraction',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='administration.client'),
        ),
        migrations.AddField(
            model_name='clientinteraction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyasset',
            name='current_holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='held_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractgenerator',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='administration.client'),
        ),
        migrations.AddField(
            model_name='contractgenerator',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['created_at'], name='administrat_created_0fc9e9_idx'),
        ),
        migrations.AddIndex(
            model_name='clientdocument',
            index=models.Index(fields=['created_at'], name='administrat_created_ca4639_idx'),
        ),
        migrations.AddIndex(
            model_name='clientinteraction',
            index=models.Index(fields=['created_at'], name='administrat_created_a5aa72_idx'),
        ),
        migrations.AddIndex(
            model_name='companyasset',
            index=models.Index(fields=['created_at'], name='administrat_created_8e09f4_idx'),
        ),
        migrations.AddIndex(
            model_name='contractgenerator',
            index=models.Index(fields=['created_at'], name='administrat_created_ee2922_idx'),
        ),
        migrations.AddIndex(
            model_name='employeedocument',
            index=models.Index(fields=['created_at'], name='administrat_created_e93cae_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['created_at'], name='administrat_created_2c7047_idx'),
        ),
    ]
