# Generated by Django 5.2.16 on 2026-08-08 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_encrypt_document_names'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contact',
            new_name='administrat_created_ca5539_idx',
            old_name='administrat_created_ct001_idx',
        ),
    ]
