# Generated by Django 5.2.16 on 2026-08-16 17:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100)),
                ('audience', models.CharField(choices=[('PUBLIC', 'Public'), ('INTERNE', 'Interne')], default='PUBLIC', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'question'],
                'abstract': False,
                'indexes': [models.Index(fields=['created_at'], name='support_faq_created_93f536_idx'), models.Index(fields=['audience', 'is_published'], name='support_faq_audienc_fc8bfa_idx')],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visitor_name', models.CharField(max_length=255)),
                ('visitor_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('OUVERT', 'Ouvert'), ('EN_COURS', 'En cours'), ('FERME', 'Fermé')], default='OUVERT', max_length=10)),
                ('access_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender_type', models.CharField(choices=[('VISITEUR', 'Visiteur'), ('STAFF', 'Équipe')], max_length=10)),
                ('body', models.TextField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.supportticket')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['created_at'], name='support_sup_created_83a137_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status'], name='support_sup_status_c35d7c_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['access_token'], name='support_sup_access__ad1535_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketmessage',
            index=models.Index(fields=['created_at'], name='support_tic_created_087850_idx'),
        ),
    ]
