# Generated by Django 5.2.16 on 2026-08-17 01:49

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_core_docume_content_a1b2c3_idx_core_docume_content_72d5a0_idx_and_more'),
        ('procurement', '0002_supplierinvoice_cash_entry'),
        ('treasury', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='procurementrequest',
            new_name='procurement_status_146396_idx',
            old_name='procurement_p_status_x9y8z7_idx',
        ),
        migrations.RenameIndex(
            model_name='supplier',
            new_name='procurement_name_04b689_idx',
            old_name='procurement_s_name_a1b2c3_idx',
        ),
        migrations.AlterField(
            model_name='supplierinvoice',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.18'), max_digits=4),
        ),
        migrations.AlterField(
            model_name='supplierquote',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.18'), max_digits=4),
        ),
        migrations.AddIndex(
            model_name='procurementrequest',
            index=models.Index(fields=['created_at'], name='procurement_created_815c47_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['created_at'], name='procurement_created_983295_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierinvoice',
            index=models.Index(fields=['created_at'], name='procurement_created_eedcc8_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierquote',
            index=models.Index(fields=['created_at'], name='procurement_created_d0840c_idx'),
        ),
    ]
