# Generated by Django 5.2.16 on 2026-08-08 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='channelmetadata',
            new_name='messaging_c_created_6183b9_idx',
            old_name='messaging_cm_created_idx',
        ),
        migrations.RenameIndex(
            model_name='channelmetadata',
            new_name='messaging_c_type_6e1e24_idx',
            old_name='messaging_cm_type_idx',
        ),
        migrations.RenameIndex(
            model_name='channelparticipant',
            new_name='messaging_c_created_dcce25_idx',
            old_name='messaging_cp_created_idx',
        ),
    ]
