# Generated by Django 5.2.16 on 2026-08-17 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0008_documentattachment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='documentattachment',
            new_name='core_docume_content_72d5a0_idx',
            old_name='core_docume_content_a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='documentattachment',
            new_name='core_docume_documen_a61efe_idx',
            old_name='core_docume_document_x9y8z7_idx',
        ),
        migrations.AddIndex(
            model_name='documentattachment',
            index=models.Index(fields=['created_at'], name='core_docume_created_123edb_idx'),
        ),
    ]
