# Generated by Django 5.2.16 on 2026-08-31 17:01

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_core_docume_content_a1b2c3_idx_core_docume_content_72d5a0_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentattachment',
            name='file',
            field=models.FileField(storage=core.models.attachment_storage, upload_to='documents/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), core.models.validate_document_attachment_size]),
        ),
    ]
