# Generated by Django 5.2.16 on 2026-09-09 09:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_documentattachment_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(max_length=512, unique=True)),
                ('platform', models.CharField(choices=[('WEB', 'Navigateur'), ('ANDROID', 'Android'), ('IOS', 'iOS')], default='WEB', max_length=10)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['created_at'], name='core_pushde_created_29e605_idx'), models.Index(fields=['user', '-last_seen_at'], name='core_pushde_user_id_93ba6e_idx')],
            },
        ),
    ]
