# Generated by Django 5.2.16 on 2026-08-31 00:55

import django.db.models.deletion
import django.utils.timezone
import django_cryptography.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_rename_administrat_created_ct001_idx_administrat_created_ca5539_idx'),
        ('technique', '0002_status_priority_francais'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintainedApp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('app_type', models.CharField(choices=[('SITE_WEB', 'Site web'), ('APP_WEB', 'Application web'), ('APP_MOBILE', 'Application mobile'), ('API', 'API / service'), ('AUTRE', 'Autre')], default='SITE_WEB', max_length=20)),
                ('url', models.URLField(blank=True, help_text='URL publique de production')),
                ('description', models.TextField(blank=True)),
                ('tech_stack', models.CharField(blank=True, help_text='Ex: Next.js, Django, PostgreSQL', max_length=255)),
                ('hosting_provider', models.CharField(blank=True, help_text='Ex: Vercel, Render, OVH', max_length=255)),
                ('repository_url', models.URLField(blank=True)),
                ('admin_url', models.URLField(blank=True)),
                ('admin_username', django_cryptography.fields.encrypt(models.CharField(blank=True, default='', max_length=255))),
                ('admin_password', django_cryptography.fields.encrypt(models.CharField(blank=True, default='', max_length=255))),
                ('access_notes', django_cryptography.fields.encrypt(models.TextField(blank=True, default=''))),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('maintenance_frequency', models.CharField(choices=[('TROIS_PAR_SEMAINE', '3 fois par semaine'), ('HEBDOMADAIRE', 'Hebdomadaire'), ('BIMENSUELLE', 'Toutes les 2 semaines'), ('MENSUELLE', 'Mensuelle')], default='TROIS_PAR_SEMAINE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_maintenance_apps', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintained_apps', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintained_apps', to='administration.client')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintained_apps', to='technique.project')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaintenanceReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('OK', 'Tout fonctionne'), ('DEGRADE', 'Dégradé — à surveiller'), ('INCIDENT', 'Incident — action requise')], default='OK', max_length=10)),
                ('site_reachable', models.BooleanField(default=True, help_text='Le site/app répond')),
                ('backups_verified', models.BooleanField(default=False, help_text='Sauvegardes vérifiées')),
                ('updates_applied', models.BooleanField(default=False, help_text='Mises à jour appliquées')),
                ('ssl_valid', models.BooleanField(default=True, help_text='Certificat SSL valide')),
                ('summary', models.TextField(help_text='Ce qui a été fait / constaté')),
                ('next_actions', models.TextField(blank=True, help_text='À faire au prochain passage')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='technique.maintainedapp')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-performed_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaintenanceServiceAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_name', models.CharField(help_text='Ex: Cloudinary, Supabase, SendGrid', max_length=255)),
                ('url', models.URLField(blank=True)),
                ('username', django_cryptography.fields.encrypt(models.CharField(blank=True, default='', max_length=255))),
                ('password', django_cryptography.fields.encrypt(models.CharField(blank=True, default='', max_length=255))),
                ('notes', django_cryptography.fields.encrypt(models.TextField(blank=True, default=''))),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_accounts', to='technique.maintainedapp')),
            ],
            options={
                'ordering': ['service_name'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='maintainedapp',
            index=models.Index(fields=['created_at'], name='technique_m_created_52a14e_idx'),
        ),
        migrations.AddIndex(
            model_name='maintainedapp',
            index=models.Index(fields=['is_active'], name='technique_m_is_acti_8304ad_idx'),
        ),
        migrations.AddIndex(
            model_name='maintainedapp',
            index=models.Index(fields=['assigned_to'], name='technique_m_assigne_fa5c2f_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancereport',
            index=models.Index(fields=['created_at'], name='technique_m_created_97a267_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancereport',
            index=models.Index(fields=['app', '-performed_at'], name='technique_m_app_id_e7d348_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancereport',
            index=models.Index(fields=['status'], name='technique_m_status_cd6faa_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceserviceaccount',
            index=models.Index(fields=['created_at'], name='technique_m_created_598962_idx'),
        ),
    ]
