# Generated by Django 5.2.16 on 2026-08-31 11:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_rename_administrat_created_ct001_idx_administrat_created_ca5539_idx'),
        ('technique', '0003_maintainedapp_maintenancereport_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='technique_p_status_3c2873_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['client'], name='technique_p_client__cd6e2f_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['project_manager'], name='technique_p_project_04567d_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created_at'], name='technique_t_created_5aa348_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'status'], name='technique_t_project_ee8cce_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_to'], name='technique_t_assigne_38b423_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['phase'], name='technique_t_phase_i_cbc2d3_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['-priority', 'due_date'], name='technique_t_priorit_5bdf72_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status'], name='technique_t_status_fabc50_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['project'], name='technique_t_project_c86076_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['assigned_developer'], name='technique_t_assigne_9bf65f_idx'),
        ),
    ]
